# This Makefile in included by architectures that select time-win
# as a default, or by builds with explicit TIME=win.
# Object files are added straight, as they are always needed

OBJ-y += \
	time-cygwin/cygwin-time.o \
	time-cygwin/cygwin-socket.o 
